### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by annakijas1** [BCDigSchol/antiphoner-site#10]
When hovering over the tabs in navigation menu with mouse they sometimes hide before you have a chance to click on one. Can this be improved? 
![screen shot 2016-08-31 at 4 15 51 pm](https://cloud.githubusercontent.com/assets/6841932/18144790/65697000-6f96-11e6-90d7-43dd3cfeec5e.png)

**Comment by ChristopherHP** [comment]
The timing might need to be adjusted in the "dropotron.min.js" file. Not my forte, however. @Otterfan might be able to assist with this.

**Comment by Otterfan** [comment]
Yep, the menu hide delay was a dropotron setting. I'm going to extend it from 250ms to 700ms. That should be long enough without being annoying.
