### ISSUE TITLE
Table padding

### ISSUE THREAD

**Issue by annakijas1** [BCDigSchol/antiphoner-site#11]
@ChristopherHP Is it possible to space out the columns better on the [Novice's Guide page](http://burnsantiphoner.bc.edu/novices-guide/)? Specifically "Incipit" column to have longer lines of text instead of having to break across several lines.

**Comment by ChristopherHP** [comment]
Not if you want all the columns to be equally sized. Otherwise, you might need to in and add widths manually to each row or cell.

**Comment by annakijas1** [comment]
That's what I figured. I think its more important that the columns are equally sized.
