### ISSUE TITLE
Strange link 

### ISSUE THREAD

**Issue by annakijas1** [BCDigSchol/antiphoner-site#12]
On [Description](http://burnsantiphoner.bc.edu/description/) page this sentence contains a link, but for some reason the full sentence is underlined as if it was all one link `<p>For a closer examination of the text and music hands in each part of the book, see <a href="http://burnsantiphoner.bc.edu/structure/" target="_blank">Summary of contents, structure, and copying</a>.</p>` @ChristopherHP or @Otterfan  any thoughts?

**Comment by ChristopherHP** [comment]
When I look at the code, the first half of the sentence has a blank <a> tag. If this is input manually, check to see if there are any open tags around that sentence.

**Comment by annakijas1** [comment]
I figured it out. I missed an </a> tag.
