### ISSUE TITLE
Table adjustments

### ISSUE THREAD

**Issue by annakijas1** [BCDigSchol/antiphoner-site#2]
Tables on "[Novice's Guide](http://burnsantiphoner.bc.edu/novices-guide/)" [beginning after the sentence "The chants, on casual inspection, appear..." through fol. 49v should appear with equal spacing between columns.

**Comment by ChristopherHP** [comment]
Are you looking for something like the image below (I added obvious border lines between TDs to highlight the changes I was making, they aren't in the code I'm adding below):

![8-25-2016 10-24-32 am](https://cloud.githubusercontent.com/assets/8724380/17972893/5fc5b894-6aae-11e6-8895-24909b8e6d0b.png)

To achieve something like that, add this to your style sheet:

`#Table1 table, #Table2 table, #Table3 table, #Table4 table, #Table5 table {
    table-layout: fixed !important;
}

#Table1 table td, #Table2 table td, #Table3 table td, #Table4 table td, #Table5 table td  {
    text-align: left;
    padding: 0 5px;
}`

**Comment by annakijas1** [comment]
Added this to the /css/main.scss file and it adjusted the spacing between columns
