### ISSUE TITLE
Viewer - image size

### ISSUE THREAD

**Issue by annakijas1** [BCDigSchol/antiphoner-site#3]
Adjust the image so it fills the screen a little better; adjust so it doesn't creep into footer.

**Comment by ChristopherHP** [comment]
On my screen, the image portion of the viewer is always just below the end of my browser, regardless of window size.

![viewer01](https://cloud.githubusercontent.com/assets/8724380/17944260/f392f836-6a0c-11e6-9a65-85c7d2d987ae.png)

When I chose the full screen mode, part of the information is hidden in the header. 
![viewer02](https://cloud.githubusercontent.com/assets/8724380/17944267/00d07de8-6a0d-11e6-80e3-4e097e7682c3.png)

By the way, my browser is Firefox 45.3

**Comment by annakijas1** [comment]
Ben was going to see if he could get the image to fill the left window a bit more (currently default is zoom level 2). The image hangs over the footer area and needs to be adjusted. Full screen mode does act funny. I've been using Chrome and this happens here, too.

**Comment by Otterfan** [comment]
I think I've got this fixed, at least on the screens I've tried. Feel free to re-open!
