### ISSUE TITLE
Navigation for mobile/device

### ISSUE THREAD

**Issue by annakijas1** [BCDigSchol/antiphoner-site#4]
Navigation menu on antiphoner site does not work when in responsive mode.

**Comment by ChristopherHP** [comment]
As far as I can see, there is no CSS telling #navPanel to go from "transform: translateX(-275px);" to "translateX(0px)" when the nav button is clicked. The nav button inserts .navPanel-visible into the body, so I'm looking for something like ".navPanel-visible #navPanel".

Add the following to the style sheet (within the media query):

`.navPanel-visible #navPanel {
    transform: translateX(0px) !important;
}`

**Comment by annakijas1** [comment]
Added 
`.navPanel-visible #navPanel { transform: translateX(0px) !important; }`
to /_sass/lib/_build.scss and it works
