### ISSUE TITLE
Search function in Viewer

### ISSUE THREAD

**Issue by annakijas1** [BCDigSchol/antiphoner-site#5]
Search function needs some tweaking. Dropdown menu for fields (i.e. genre, feast, etc.) data parsing is a bit off. For example Mode 2 pulls in 2S, Mode 7 doesn't pull in anything. Also check with the other dropdown fields for strange data parsing behavior.

**Comment by Otterfan** [comment]
There was some trouble with the Cantus feasts. I've fixed that in c7824b6.
